title: TownSuite.WorkQueues
description: A lightweight message bus and work queue for .NET, backed by SQL Server, PostgreSQL, Redis, or SQLite.

permalink: pretty
url: "https://townsuite.github.io"
baseurl: "/TownSuite.WorkQueues"

github_repo: "https://github.com/TownSuite/TownSuite.WorkQueues"

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
